### ISSUE TITLE
Please, do the checking of string length with mb_strlen

### ISSUE THREAD

**Issue by olek07** [einpraegsam/femanager#10]
strlen('Ö') = 2. It's not right in the `validateMin` function

```
protected function validateMin($value, $validationSetting)
    {
        if (strlen($value) < $validationSetting) {
            return false;
        }
        return true;
}
```

**Comment by einpraegsam** [comment]
This is part of the extension. What should I do with this? If you are reporting a bug, please also write how to reproduce the bug. Thx

**Comment by olek07** [comment]
strlen('Ö') = 2. It's not right
mb_strlen('Ö') = 1. It's right

**Comment by einpraegsam** [comment]
Thx, I pushed a fix to develop branch. Ready for upcoming release.

**Comment by olek07** [comment]
thank you
