### ISSUE TITLE
Installation freezes

### ISSUE THREAD

**Issue by qwertas666** [einpraegsam/femanager#11]
Installation freezes in a blank TYPO3 installation and destroys the access to the backend.

femanager 3.0.0
TYPO3 8.7.4
PHP: 7.0.21
MYSQL: 5.5.57
Browser: Firefox 54.0.1

**Comment by einpraegsam** [comment]
Is your TYPO3 running in composer or classic mode?

**Comment by einpraegsam** [comment]
Any feedback?

**Comment by qwertas666** [comment]
TYPO3 ist running in classic mode.

**Comment by einpraegsam** [comment]
ok, can you please try femanager 3.0.1, clear caches, adding via Extension Manager?

**Comment by einpraegsam** [comment]
Pls see further notices at https://github.com/einpraegsam/femanager/issues/12
