### ISSUE TITLE
After installation, i get this error

### ISSUE THREAD

**Issue by Regna91** [einpraegsam/femanager#12]
After the installation via extension manager  i get following error:
`Class 'In2code\Femanager\Domain\Model\Log' not found `

If I download the femanager 3.0.1 manually and upload it, I get following error:
`unserialize() expects parameter 1 to be string, null given `

PHP: 7.0.21
T3: Typo3 8.7.4
OPcache: 7.0.21

If i tried to delete the cache in install tool, i get the same error.

**Comment by einpraegsam** [comment]
1) I created a new FAQ entry to the first problem. See https://github.com/einpraegsam/femanager/blob/develop/Documentation/FAQ/Index.rst#q-class-in2codefemanagerdomainmodellog-not-found---what-can-i-do for some details and how to fix it.

2) It seems that you are right. If configuration is missing the error comes up. I pushed a fix to develop branch. Ready for the upcoming release.

**Comment by einpraegsam** [comment]
P.S.: I just released version 3.0.2 that should fix your problem 2)
