### ISSUE TITLE
Add User in femanager-Backend 

### ISSUE THREAD

**Issue by qwertas666** [einpraegsam/femanager#13]
In TYPO3 Version 7.6.21 (femanager Version 2.6.0) and 8.7.4 (femanager Version 3.0.2) --> FE-Manager Backend --> I can't add a new User via "add"-Button in the Table. 

In TYPO3 6.2.29 (femanager Version 1.5.2) add User in backend works nice.

**Comment by einpraegsam** [comment]
Thx, seems that you're right with the bug issue.
I will fix it as soon as I have time for it.

**Comment by einpraegsam** [comment]
Fixed in develop branch. Ready for upcoming release.
