### ISSUE TITLE
jQuery error

### ISSUE THREAD

**Issue by carodb** [einpraegsam/femanager#14]
As already reported in TYPO3 forge, there is an error in the JS. When loading the page femanager is included on, the console outputs the error "$ is not a function". $ should be passed as parameter in jQuery(document).ready or initialized as variable in Validation.js and for createUploader() in Femanger.js

**Comment by einpraegsam** [comment]
I do not have this error in my console. Pls write your jQuery version and your specials (like jQuery is running in noconflict mode or so).

**Comment by carodb** [comment]
jQuery version 3.2.1 and noConflict is enabled

**Comment by einpraegsam** [comment]
I don't want to investigate time in that issue at the moment. But feel free to do a PR.
