### ISSUE TITLE
ConfigurationManager returns no Settings in combination with flux extension

### ISSUE THREAD

**Issue by ervaude** [einpraegsam/femanager#17]
Hi,

when using femanager together with EXT:flux, I encountered the issue that, since flux registers a custom ConfigurationManager implementation, the Validators of femanager fail to receive their settings TS.

I know that this is not the fault of this extension, however I'd like to propose a PR, since I think changing this is correct regardless of the flux interaction.

Since the issue only occurs when `CONFIGURATION_TYPE_FRAMEWORK` is used (wich is weird ...) I think in those places where the only needed configuration are the settings anyway, we can simply aks for `CONFIGURATION_TYPE_SETTING` instead.

**Comment by moger-xx** [comment]
The issue seems is occuring again running femenager/dev-develop, TYPO3 8.7.7 and Flux 8.2.1.

**Comment by moger-xx** [comment]
@ervaude which flux version did you use / which should be compatible by now?

**Comment by moger-xx** [comment]
when using
$config = $this->configurationManager->getConfiguration( ConfigurationManagerInterface::CONFIGURATION_TYPE_SETTINGS, 'Femanager' );

it works.
