### ISSUE TITLE
[FEATURE] HTML5 Validation

### ISSUE THREAD

**Issue by ervaude** [einpraegsam/femanager#21]
The current state of the Field-Partials does not allow for any HTML-5 validation out of the box (one can always override the partials of course).

Do you want such a feature?

An implementation for required and email, should be fairly easy (I could provide a PR).

However a full implementation of all capabilitties of HTML5 fomrfield validation would be a greater task, I guess.

**Comment by einpraegsam** [comment]
I would like to see a PR with type=email and a required attribut (if it's set via TypoScript). At the moment there are no plans to do something in this way.
Nevertheless I will close this issue for new. Pls reopen if needed.
