### ISSUE TITLE
Make "Show action" as non cacheable controller action 

### ISSUE THREAD

**Issue by s-nunez** [einpraegsam/femanager#25]
In the frontend plugin I have selected the view "Detail" and as User to show "Logged in FE User". 

I get always the same user data, although I log me in with different frontend users.

Should the action "Show" be defined as non cacheable controller action in ext_localconf.php?

**Comment by tmotyl** [comment]
@s-nunez what piece of information on Detail view is fe_user specific?

**Comment by einpraegsam** [comment]
Seems to be a caching issue to me. I think that the detail view can not be cached for this feature `Logged in FE User` - I will push a fix

**Comment by einpraegsam** [comment]
Pushed to develop branch. Thx for reporting.

**Comment by s-nunez** [comment]
Perfect! 
Thank you very much for your extrem fast help :)
