### ISSUE TITLE
TYPO3 exception when trying to delete image

### ISSUE THREAD

**Issue by benjamingries** [einpraegsam/femanager#28]
Hi, 

I got a TYPO3 exception when trying to delete a image. Error message shown is:

The controller "User" is not allowed by plugin "Pi1". Please check for TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin() in your ext_localconf.php

I think it is a bug. Or is there anything I am doing wrong?

TYPO3: 8.7.7
femanager: 3.1.2

Regards
Benjamin

**Comment by einpraegsam** [comment]
Works as expected on my testparcours. 
What if you add an new page for testing and add just add one content element (a femanager plugin with the edit settings + image) on this page? Does that work?
<img src="https://s.nimbus.everhelper.me/attachment/1164194/repnlzhugnuupkotsi6h/262407-MJGYxxdBoE3QX7rG/screen.png" />

**Comment by benjamingries** [comment]
After deleting the old plugin and creating a new plugin (with the same settings) the problem was solved. Thanks, Alex!
