### ISSUE TITLE
TYPO3 exception after changing uploadFolder path

### ISSUE THREAD

**Issue by benjamingries** [einpraegsam/femanager#29]
Hi, 

I changed the uploadFolder path of the extension to uploads/pics/ and now I get the error:

#1314516809: File /uploads/pics/somefilename.jpg/ does not exist.

There is a trailing slash at the end. Is it a bug or a wrong configuration of htaccess file? Normal images with jpg format could be loaded without trailing slash.

TYPO3: 8.7.7
femanager: 3.1.2

Regards
Benjamin

**Comment by einpraegsam** [comment]
Pls send me the exact configuration how you changed the upload folder.

If I use constants like
`plugin.tx_femanager.settings.uploadFolder = fileadmin/users_changed/` everything works as expected (also the deletion of the image afterwords).

**Comment by benjamingries** [comment]
My configuration was plugin.tx_femanager.settings.uploadFolder = uploads/pics/

After changing my configuration to plugin.tx_femanager.settings.uploadFolder = fileadmin/user_upload/benutzer/ the problem was solved.

In general I guess it should be possible to use the uploads/pics/ as uploadFolder

**Comment by einpraegsam** [comment]
Do you have a file storage with uploads created in your TYPO3? 
Note: Images of fe_users are created via FAL now in TYPO3 8 - so the folder is not uploads/ any more by default

**Comment by benjamingries** [comment]
It was my fault again. I didn't know that the images of fe_users were created via FAL so that the uploads folder is not allowed there.

**Comment by einpraegsam** [comment]
Fixed with femanager 3.1.3
