### ISSUE TITLE
Sender name for user notification email not set correctly

### ISSUE THREAD

**Issue by Josta** [einpraegsam/femanager#30]
There's a small bug that makes it impossible to set the sender name for the notification mail that is sent to users after their profile has been confirmed.

In AbstractController.php line 281 it says

`$this->settings['settings']['new']['email']['createUserNotify']['sender']['name']['value']`

This should probably be

`$this->settings['new']['email']['createUserNotify']['sender']['name']['value']`

**Comment by einpraegsam** [comment]
Thx for digging into this issue. I pushed a fix to develop branch. Ready for the upcoming release.
