### ISSUE TITLE
Detail View: Show only FE-User from special Directory - is it possible?

### ISSUE THREAD

**Issue by webdev2027** [einpraegsam/femanager#31]
Hi Alex.

I'm using femanager 2.6.0, because my Website is still running with `TYPO3 CMS 7.6`.
I have imported a lots of users via LDAP. F.e. in folder '20' are 10.000 FE-Users, folder '21' have 8.000 FE-User... and I also use `Ext: seminars` with temp. fe-users (`Ext: onetimeaccount`) ... my `fe_users` will be increase ...

I'm insert the femanager-Plugin > detail view > select/option field with more than >18.000 Users. But I also select the 'Storrage folder 20', not recursive - but all fe-users will shown ...

Maybe you've fix this in newer versions, I don't know.
How can I show my `fe_users` in Flexform from folder xy only? Is this possible? Thanks for your help.

![fe_manager1](https://user-images.githubusercontent.com/5501876/32789037-170898a8-c95b-11e7-9792-6f4e610c0f55.jpg)

**Comment by einpraegsam** [comment]
This is a missing feature. The select box "Zu zeigender Benutzer" doesn't respect any startpoint at the moment.
I would also think about some UX improvements like adding a find wizard or so.
Nevertheless this is not planned at the moment, but you can do a PR or contact me if you are willing to sponsor it.

**Comment by einpraegsam** [comment]
Hello again,

I pushed your feature wish to develop branch. This will be available with the upcoming minor release.
Now the starting point(s) will be respected and of course the recursive depth.

But there is one think that you should have in mind: If you select a user storage, you have to save the plugin once. Now the list is filtered.

Cheers, Alex
