### ISSUE TITLE
Image upload not working

### ISSUE THREAD

**Issue by mhadar** [einpraegsam/femanager#32]
When I use Image field in user edit profile form and tries to submit with image inserted it says:

Argument 1 passed to In2code\Femanager\DataProcessor\ImageManipulation::getNewImageName() must be of the type array, string given, called in /usr/www/users/syuivz/dev-lifetimes/typo3conf/ext/femanager/Classes/DataProcessor/ImageManipulation.php on line 37

**Comment by mhadar** [comment]
Solved, the problem was missing: enctype="multipart/form-data" in <form> tag

**Comment by einpraegsam** [comment]
thx for your final feedback
