### ISSUE TITLE
Notification for user

### ISSUE THREAD

**Issue by NiklasLazinbee** [einpraegsam/femanager#33]
Hey a great work!
But there is some thing I miss. I want to implement the admin confirmation process. These steps are possible:
1. The user creates a account 
2. The user gets an email and confirm the account with the link
3. The admin gets an email for the registration and confirm the account with the link
4. The admin gets an Email that the registration is confirmed

But who notifys the user that his account is now ready? Is there a possibility to send the user an notification email at the end of this process?

Geetings 
Niklas

**Comment by einpraegsam** [comment]
Hi Niklas,

yes, seems that this is a missing feature. Are you willing to sponsor it or do a PR?

Alex

**Comment by NiklasLazinbee** [comment]
Hallo Alex,
ich antworte mal auf deutsch. Ich denke die Extension ist ziemlich gut, trotz des fehlenden Features. Ich muss schauen, ob bezüglich Sponsoring am Endes des Projekts noch etwas übrig bleibt. Was meinst du mit PR?

Beste Grüße
Niklas

**Comment by einpraegsam** [comment]
PR => Pull Request
Everone can contribute with code :)
