### ISSUE TITLE
additional filters in search form

### ISSUE THREAD

**Issue by heikohaensge** [einpraegsam/femanager#34]
We added an additional field 'topics' to the table fe_users by a custom extension. This field can hold a comma separated list of integers. 
Now we would like to add an additional filter to the search form. 
The filter should be a dropdown menu to select one of the predefined 'topics'. 
The search should consider the seleted 'topic'-value and restrict the search result list of users accordingly. 
Is this possible? 
And if yes, how to do it?
Thanks in advance for the advice.

**Comment by einpraegsam** [comment]
I don't think this is possible atm
