### ISSUE TITLE
Registration: Validation error message

### ISSUE THREAD

**Issue by Hobokens** [einpraegsam/femanager#36]
TYPO3 8.7.8, femanager 3.2.0
The error message for user group is in German
'Feld 0 ist ein Pflichtfeld'

Regards
Hobokens

**Comment by einpraegsam** [comment]
If I search for "Pflichtfeld" in Resources/Private/Language/ there are no hits. Just english labels.

**Comment by Hobokens** [comment]
Sorry for adding one more comment. 

I tried to define the german translation in TS setup with:
plugin.tx_femanager._LOCAL_LANG.de {
	tx_femanager_domain_model_user.usergroup = Mitgliedschaft
}

to get ''Feld Mitgliedschaft ist ein Pflichtfeld'' (This is the standard formulation if a field remains empty.) But I still get 'Feld 0 ist ein Pflichtfeld'. So what can I do to replace the '0'?

Regards
Hobokens

**Comment by einpraegsam** [comment]
Thx, it seems that you're right. While the serverside validation works as expected, JS validation seems to be broken on this point. I will push a fix.

**Comment by einpraegsam** [comment]
Fix will be available with version 4.0.0. Pls be patient up to this point.

**Comment by Hobokens** [comment]
thanks a lot.
