### ISSUE TITLE
Call to undefined method In2code\Femanager\Utility\FileUtility::getUploadFolderFromTca() 

### ISSUE THREAD

**Issue by zbychu555** [einpraegsam/femanager#4]
After update to the newest dev I have an error:
 `Call to undefined method In2code\Femanager\Utility\FileUtility::getUploadFolderFromTca() `
This error occurs because of: 
https://github.com/einpraegsam/femanager/blob/develop/Classes/Controller/AbstractController.php#L432

**Comment by einpraegsam** [comment]
Thx for the hint. I fixed that.
