### ISSUE TITLE
Error "profile has been deleted" when trying to confirm registration by user

### ISSUE THREAD

**Issue by eheimgartner** [einpraegsam/femanager#40]
We use femanager 1.5.0 in TYPO3 6.2.10, our website is:
http://www.nse.ch/interner-bereich/nse-ag-login/

In several cases, it has been observed that new users cannot confirm their registration. The error message below is displayed. We have set 'confirmedbyuser' = 1 and 'confirmedbyadmin' = 1.
When we look at the affected records in the data table 'fe_users', the flags 'disable' and 'deleted' are both set to 1. This might be an indication for the cause of the problem.
![2017-12-05 15_37_53-wg_ bitte bestatigen sie ihre profil-registrierung - nachricht html](https://user-images.githubusercontent.com/34276527/33612601-620da99c-d9d2-11e7-88f3-fd671e6689da.png)

The way we had worked around this problem, was to create the user in the backend. Unfortunately, we cannot upgrade TYPO3 to version 7.x or 8.x at the moment.

**Comment by einpraegsam** [comment]
1.5.0 is not supported any more - sorry.
We're currently working on a 4.0 release.

**Comment by einpraegsam** [comment]
BTW: You should really upgrade your TYPO3

**Comment by eheimgartner** [comment]
Oh yes, we know we should upgrade. The question is, whether an upgrade would solve the problem. The problem might also be due to some bad side effect of another extension.

**Comment by einpraegsam** [comment]
I did not see a problem like you described - so I can't give you a guaranty that your problem is solved. Nevertheless is a software upgrade to the newest version always the first step in my eyes.
