### ISSUE TITLE
Errro when opening BE module

### ISSUE THREAD

**Issue by millemedia** [einpraegsam/femanager#400]
Dear Alex,

I am currently working in a composer installation (TYPO3 V10, femanager 6.3.1). The page uid is other then 1. 
When I open the BE module I get an error:

Oops, an error occurred!
Could not fetch page data for uid 1.
More information regarding this error might be available online.

Kind regards

Andreas

**Comment by sbusemann** [comment]
Please set set module.tx_femanager.settings.configPID to the root page ID of your site

See: https://docs.typo3.org/p/in2code/femanager/master/en-us/Installation/Index.html#configuration
