### ISSUE TITLE
Problem in flex form

### ISSUE THREAD

**Issue by joka123** [einpraegsam/femanager#5]
I use the devlop source with typo3 8.7.3 and php 7. when i try to set the view in the contentelement i got the error:
Uncaught TYPO3 Exception
#1476107295: PHP Warning: Illegal string offset 'switchableControllerActions' in /kunden/180927_90429/typo3_src_8LTS/typo3/sysext/core/Classes/DataHandling/DataHandler.php line 3110 (More information)

TYPO3\CMS\Core\Error\Exception thrown in file
/kunden/180927_90429/typo3_src_8LTS/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 112.

the solution for me was to change
`<T3DataStructure>
    <meta>
        <langDisable>1</langDisable>
    </meta>
    <sheets>
        <main>`
to
`<T3DataStructure>
    <meta>
        <langDisable>1</langDisable>
    </meta>
    <sheets>
        <sDEF>`

and set it in all displayCond
`<displayCond><![CDATA[FIELD:sDEF.switchableControllerActions:=:New->new;New->create;New->createStatus;New->confirmCreateRequest;]]></displayCond>`

**Comment by einpraegsam** [comment]
I'm working on develop branch (for TYPO3 8.x):
What should I exactly do to see the error? Adding a Plugin and then?

**Comment by einpraegsam** [comment]
No feedback, so I will close this issue
