### ISSUE TITLE
Fatal error when using embedded image in email

### ISSUE THREAD

**Issue by millemedia** [einpraegsam/femanager#7]
When embedImage is used for mail you will get a fatal error for all emails but not createUserConfirmation. 

Error;
#1476107295: PHP Warning: explode() expects parameter 2 to be string, object given. See attached file.
[TYPO3 Exception.zip](https://github.com/einpraegsam/femanager/files/1193050/TYPO3.Exception.zip)

**Comment by einpraegsam** [comment]
Thx for the hint, I will check this.
BTW: I think that you're writing about branch develop and TYPO3 8?

**Comment by millemedia** [comment]
Hi Alex, yes, it's TYPO3 8 branch develop.

**Comment by millemedia** [comment]
Hi Alex,
yes it's TYPO3 8 branch develop.

**Comment by einpraegsam** [comment]
Did you embed an image via TypoScript? If so, pls write me your configuration.

**Comment by millemedia** [comment]
Here it is:
For all mails the same.
					embedImage = COA
					embedImage {
						10 = IMG_RESOURCE
						10 {
							wrap = |,
							file.import = uploads/pics/
							file.import.field = image
							file.import.listNum = 0
							file.maxW = 120
							file.maxH = 120
						}

						20 = TEXT
						20.value = fileadmin/templates/img/logo.png
					}

**Comment by einpraegsam** [comment]
Thx for clearify.
Can you please test the current develop branch? I made some changes and images should be rendered in mails again:
<img src="https://box.everhelper.me/attachment/1043526/84725fb7-0b3e-4c40-b52e-29d7620777bb/262407-cZO9V15V7hEcs5eF/screen.png" />

**Comment by millemedia** [comment]
Perfect! It works!
Thanks a lot
