### ISSUE TITLE
Exception after Frontend 'Edit'

### ISSUE THREAD

**Issue by SicorDev** [einpraegsam/femanager#8]
Hello there,

I downloaded the dev version since I'm working on a 8.7.4 page. We basically only need femanager for a change password dialog. After Saving the method 'getDirtyPropertiesFromUser' from UserUtility.php crashes in the final branch when calling ObjectUtility::implodeObjectStorageOnProperty for the property 'image'. 

Since we only need to change the password, we simply added 'image' to the ignore array a few lines above, but I thought you might want to investigate anyway.

Greetings,
Manuel

**Comment by einpraegsam** [comment]
Thx Manual for your feedback.
What is your configuration? Maybe you can send me a screenshot of your plugin?

Alex

**Comment by SicorDev** [comment]
It's really bare bones. Nothing is filled in, except the password. (If you add 'redirectPage' it crashes also IIRC, since there's no getter/setter for it in the model)

![grafik](https://user-images.githubusercontent.com/24271592/28874041-6dba14f0-7790-11e7-8f27-4477f806eee4.png)

Some TS ist set, all harmless I think:
plugin.tx_femanager.settings.edit.validation.email {
  required = 0
  email = 0
}

plugin.tx_femanager.settings.edit.redirect = TEXT
plugin.tx_femanager.settings.edit.redirect.typolink.parameter = 776
plugin.tx_femanager.settings.edit.redirect.typolink.returnLast = url

And a few modifications we did to the edit template.

**Comment by einpraegsam** [comment]
ok, it took me a while to find out that the exception only occurs if the logged in fe_user has no attached image.
I will fix it asap.

**Comment by einpraegsam** [comment]
Thx again for your feedback. Fixed in develop branch.
